name: "Brian Santero"
description: "As trombonist and technologist, Brian Santero is always looking for excellent ways to express himself creatively."
url: "http://localhost:4000"
paginate: 10
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
collections:
  hidden:
    output: true
    title: Hidden
    permalink: /behind/the/:path/
  portfolio:
    output: true
    title: portfolio
    permalink: /portfolio/:path/
