name: "Brian Santero"
description: "Trombonist and technologist, Brian Santero is always looking for excellent ways to express himself creatively."
url: "http://localhost:4000"
paginate: 10
markdown: kramdown
permalink: pretty
collections:
  hidden:
    output: true
    title: Hidden
    permalink: /behind/the/:path/
  trombone:
    output: true
    title: trombone
    permalink: /trombone/:path/
textile_ext: "textile,txtl,tl"
